export const API_CREATE_DEPARTMENT = 'ACD';
export const UPDATE_DEPARTMENT_MANAGER_LIST = 'UDML';
export const UPDATE_DEPARTMENT_MANAGER_LIST_SUCCESS = 'UDML1';

export const API_UPDATE_DEPARTMENT_NAME = 'AUDN';
export const UPDATE_DEPARTMENT_NAME ='UDN'
export const UPDATE_DEPARTMENT_NAME_SUCCESS = 'UDN1';


export const API_UPDATE_DEPARTMENT_STATUS = 'AUDS';
export const UPDATE_DEPARTMENT_STATUS = 'UDS';
export const UPDATE_DEPARTMENT_STATUS_SUCCESS = 'UDS1';




