export const API_CREATE_DEPARTMENT = '1';
export const UPDATE_DEPARTMENT_MANAGER_LIST = '2';
export const UPDATE_DEPARTMENT_MANAGER_LIST_SUCCESS = '3';

export const API_UPDATE_DEPARTMENT_NAME = '4';
export const UPDATE_DEPARTMENT_NAME ='5'
export const UPDATE_DEPARTMENT_NAME_SUCCESS = '6';


export const API_UPDATE_DEPARTMENT_STATUS = '7';
export const UPDATE_DEPARTMENT_STATUS = '8';
export const UPDATE_DEPARTMENT_STATUS_SUCCESS = '9';




